name: Test and Report

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  ALLURE_VERSION: "2.32.0"
  PYTHON_VERSION: "3.11"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: PYTHON_VERSION

      - name: Install Allure
        run: |
          # 下载 Allure 二进制文件
          wget https://github.com/allure-framework/allure2/releases/download/$ALLURE_VERSION/allure-$ALLURE_VERSION.tgz
          # 解压下载的文件
          tar -zxvf allure-$ALLURE_VERSION.tgz
          
          # 将 Allure 添加到 PATH
          sudo mv allure-$ALLURE_VERSION /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          
          # 验证安装是否成功
          allure --version

      - name: Install dependencies
        run: |
          make install

      - name: Run tests and generate report
        run: make test-report

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: Coverage Report
          path: ./report/coverage

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: ./report/test
